"""first migrate

Revision ID: 2c80ce60304a
Revises: 
Create Date: 2023-07-21 15:14:18.296825

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c80ce60304a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_url_map_time_stamp', table_name='url_map')
    op.drop_table('url_map')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('url_map',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('original', sa.VARCHAR(), nullable=True),
    sa.Column('short', sa.VARCHAR(length=16), nullable=False),
    sa.Column('time_stamp', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('original'),
    sa.UniqueConstraint('short')
    )
    op.create_index('ix_url_map_time_stamp', 'url_map', ['time_stamp'], unique=False)
    # ### end Alembic commands ###
